### ISSUE TITLE
output path and filename are not joined properly

### ISSUE THREAD

**Issue by cgjosephlee** [kishwarshafin/helen#12]
`stitch.py -o .` produced a hidden file `.HELEN_consensus.fa`.

It would be better to use `os.path.join()` here:
https://github.com/kishwarshafin/helen/blob/d372a9aa6bfdcf3a54a1a34a2c449b26cc2fdf40/stitch.py#L47

**Comment by kishwarshafin** [comment]
Thanks, Joseph, for the suggestion, this is an excellent catch. Would be willing to contribute to this project by fixing this error? If yes, please fork the project, edit and create a pull request and I'll accept it. This will encourage others to find bugs and report accordingly. 

If you think the issue is too trivial to go through all these, then let me know, and I'll fix it asap.

**Comment by cgjosephlee** [comment]
Sure! It won't take too much time.
